controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheels_per_side: 1
    wheel_separation: 0.22
    wheel_radius: 0.035
    base_frame_id: base_link
    use_stamped_vel: false

# joint_state_broadcaster:
#   ros__parameters:
