# twist_mux.yaml

twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      keyboard:
        topic   : key_vel
        timeout : 0.5
        priority: 90
